export const emojisList = [
    { emoji: "🙂", description: "Slightly smiling face", unicode: "U+1F642" },
    { emoji: "😀", description: "Smiling face", unicode: "U+1F600" },
    { emoji: "😃", description: "Smiling face with big eyes", unicode: "U+1F603"} ,
    { emoji: "😄", description: "Smiling face with smiling eyes", unicode: "U+1F604" },
    { emoji: "😁", description: "Beaming face with smiling eyes", unicode: "U+1F601" },
    { emoji: "😅", description: "Smiling face with tears", unicode: "U+1F605" },
    { emoji: "😆", description: "Grinning face", unicode: "U+1F606" },
    { emoji: "🤣", description: "Rolling on the floor laughing", unicode: "U+1F923" },
    { emoji: "😂", description: "Lauging with tears", unicode: "U+1F602" },
    { emoji: "🙃", description: "Upside down face", unicode: "U+1F643" },
    { emoji: "😉", description: "Winking face", unicode: "U+1F609" },
    { emoji: "😊", description: "Smiling face with smiling eyes", unicode: "U+1F60A" },
    { emoji: "😇", description: "Smiling face with halo", unicode: "U+1F607" },
    { emoji: "😎", description: "Smiling face with sunglasses", unicode: "U+1F60E" },
    { emoji: "🤓", description: "Nerdy face", unicode: "U+1F913" },
    { emoji: "🧐", description: "Face with monocle", unicode: "U+1F9D0" },
    { emoji: "🥳", description: "Partying face", unicode: "U+1F973" },
    { emoji: "🥰", description: "Smiling face with hearts", unicode: "U+1F970" },
    { emoji: "😍", description: "Smiling face with heart eyes", unicode: "U+1F60D" },
    { emoji: "🤩", description: "Star-struck", unicode: "U+1F60D" },
    { emoji: "😘", description: "Face blowing kiss", unicode: "U+1F618" },
    { emoji: "😗", description: "Kissing face", unicode: "U+1F617" },
    { emoji: "😚", description: "Kissing face with closed eyes", unicode: "U+1F61A" },
    { emoji: "😙", description: "Kissng face with smiling eyes", unicode: "U+1F619" },
    { emoji: "😋", description: "Yummy face", unicode: "U+1F60B" },
    { emoji: "😛", description: "Face with tongue", unicode: "U+1F61B" },
    { emoji: "😜", description: "WInking face with tongue", unicode: "U+1F61C" },
    { emoji: "🤪", description: "Zanny face", unicode: "U+1F92A" },
    { emoji: "😝", description: "Squinting face with tongue", unicode: "U+1F61D" },
    { emoji: "🤑", description: "Money face with money tongue", unicode: "U+1F911" },
    { emoji: "🤗", description: "Hugs", unicode: "U+1F917" },
    { emoji: "🤭", description: "Face with hand in mouth", unicode: "U+1F92D" },
    { emoji: "🤫", description: "Shushing face", unicode: "U+1F92B" },
    { emoji: "🤔", description: "Thinkin face", unicode: "U+1F914" },
    { emoji: "😐", description: "Neutral face", unicode: "U+1F610" },
    { emoji: "🤐", description: "Zipped mouth", unicode: "U+1F910" },
    { emoji: "🤨", description: "Face with raised eyebrow", unicode: "U+1F928" },
    { emoji: "😑", description: "Expressionless face", unicode: "U+1F611" },
    { emoji: "😶", description: "Face with no mouth", unicode: "U+1F636" },
    { emoji: "😏", description: "Smirking face", unicode: "U+1F60F" },
    { emoji: "😒", description: "Unamused face", unicode: "U+1F612" },
    { emoji: "🙄", description: "Face with rolling eyes", unicode: "U+1F644" },
    { emoji: "😬", description: "Grimacing face", unicode: "U+1F62C" },
    { emoji: "😮‍💨", description: "Grimacing face", unicode: "U+1F4A8" },
    { emoji: "🤥", description: "Lying face", unicode: "U+1F925" },
    { emoji: "😪", description: "Sleepy face", unicode: "U+1F62A" },
    { emoji: "😴", description: "Sleeping face", unicode: "U+1F634" },
    { emoji: "😌", description: "Relieved face", unicode: "U+1F60C" },
    { emoji: "😔", description: "Pensive face", unicode: "U+1F614" },
    { emoji: "🤤", description: "Drooling face", unicode: "U+1F924" },
    { emoji: "😷", description: "Face with mask", unicode: "U+1F637" },
    { emoji: "🤒", description: "Face with thermometer", unicode: "U+1F912" },
    { emoji: "🤕", description: "Face with bandage", unicode: "U+1F915" },
    { emoji: "🤢", description: "Nauseous face", unicode: "U+1F922" },
    { emoji: "🤮", description: "Vomiting face", unicode: "U+1F92E" },
    { emoji: "🤧", description: "Sneezing face", unicode: "U+1F927" },
    { emoji: "🥵", description: "Hot face", unicode: "U+1F975" },
    { emoji: "🥶", description: "Cold face", unicode: "U+1F976" },
    { emoji: "🥴", description: "Woozy face", unicode: "U+1F974" },
    { emoji: "😵", description: "Face with crossed-out face", unicode: "U+1F635" },
    { emoji: "🤯", description: "Face with exploding head", unicode: "U+1F92F" },
    { emoji: "😕", description: "Confused face", unicode: "U+1F615" },
    { emoji: "😟", description: "Worried face", unicode: "U+1F61F" },
    { emoji: "🙁", description: "Slightly frowning face", unicode: "U+1F641" },
    { emoji: "☹", description: "Frowning face", unicode: "U+2639" },
    { emoji: "😮", description: "Face with open mouth", unicode: "U+1F62E" },
    { emoji: "😯", description: "Hushed face", unicode: "U+1F62F" },
    { emoji: "😲", description: "Astonished face", unicode: "U+1F632" },
    { emoji: "😳", description: "Flushed face", unicode: "U+1F633" },
    { emoji: "🥺", description: "Begging face", unicode: "U+1F97A" },
    { emoji: "😦", description: "Frowning face with open mouth", unicode: "U+1F626" },
    { emoji: "😧", description: "Angushed face", unicode: "U+1F627" },
    { emoji: "😨", description: "Fearful face", unicode: "U+1F628" },
    { emoji: "😰", description: "Anxious face with sweat", unicode: "U+1F630" },
    { emoji: "😥", description: "Sad but relieved face", unicode: "U+1F625" },
    { emoji: "😢", description: "Crying face", unicode: "U+1F622" },
    { emoji: "😭", description: "Loudly crying face", unicode: "U+1F62D" },
    { emoji: "😱", description: "Screaming face", unicode: "U+1F631" },
    { emoji: "😖", description: "Confounded face", unicode: "U+1F616" },
    { emoji: "😣", description: "Persevering face", unicode: "U+1F623" },
    { emoji: "😞", description: "Disapointed face", unicode: "U+1F61E" },
    { emoji: "😓", description: "Downcast face with sweat", unicode: "U+1F613" },
    { emoji: "😩", description: "Weary face", unicode: "U+1F629" },
    { emoji: "😫", description: "Tired face", unicode: "U+1F62B" },
    { emoji: "🥱", description: "Yawning face", unicode: "U+1F971" },
    { emoji: "😤", description: "Face with steam", unicode: "U+1F624" },
    { emoji: "😡", description: "Pouting face", unicode: "U+1F621" },
    { emoji: "😠", description: "Angry face", unicode: "U+1F620" },
    { emoji: "🤬", description: "Face with symbols on mouth", unicode: "U+1F92C" },
    { emoji: "😈", description: "Smiling face with horns", unicode: "U+1F608" },
    { emoji: "👿", description: "Angry face with horns", unicode: "U+1F47F" },
    { emoji: "💀", description: "Skull", unicode: "U+1F480" },
    { emoji: "☠", description: "Skull and cross-bone", unicode: "U+2620" },
    { emoji: "💩", description: "Pile of poo", unicode: "U+1F4A9" },
    { emoji: "🤡", description: "Clown", unicode: "U+1F921" },
    { emoji: "👹", description: "Ogre", unicode: "U+1F479" },
    { emoji: "👺", description: "Goblin", unicode: "U+1F47A" },
    { emoji: "👻", description: "Ghost", unicode: "U+1F47B" },
    { emoji: "👽", description: "Alien", unicode: "U+1F47D" },
    { emoji: "👾", description: "Alien monster", unicode: "U+1F47E" },
    { emoji: "🤖", description: "Robot", unicode: "U+1F916" },
    { emoji: "😺", description: "Grinnig cat", unicode: "U+1F63A" },
    { emoji: "😸", description: "Grinning cat with smiling eyes", unicode: "U+1F638" },
    { emoji: "😹", description: "Grinning cat with tears", unicode: "U+1F639" },
    { emoji: "😻", description: "Smiling cat with heart eyes", unicode: "U+1F63B" },
    { emoji: "😼", description: "Cat with wry smile", unicode: "U+1F63C" },
    { emoji: "😽", description: "Kissing cat", unicode: "U+1F63D" },
    { emoji: "🙀", description: "Weary cat", unicode: "U+1F640" },
    { emoji: "😿", description: "Crying cat", unicode: "U+1F63F" },
    { emoji: "😾", description: "Pouting cat", unicode: "U+1F63E" },
    { emoji: "🙈", description: "See no evil monkey", unicode: "U+1F648" },
    { emoji: "🙉", description: "Hear no evil monkey", unicode: "U+1F649" },
    { emoji: "🙊", description: "Speak no evil monkey", unicode: "U+1F64A" },
    { emoji: "🧑", description: "Person", unicode: "U+1F9D1" },
    { emoji: "👶", description: "Baby", unicode: "U+1F476" },
    { emoji: "🧒", description: "Child", unicode: "U+1F9D2" },
    { emoji: "👦", description: "Boy", unicode: "U+1F466" },
    { emoji: "👧", description: "Girl", unicode: "U+1F467" },
    { emoji: "👱", description: "Person with blonde hair", unicode: "U+1F471" },
    { emoji: "👨", description: "Man", unicode: "U+1F468" },
    { emoji: "🧔", description: "Bearded person", unicode: "U+1F9D4" },
    { emoji: "🧔‍♂‍", description: "Bearded man", unicode: "U+1F9D4" },
    { emoji: "🧔‍♀‍", description: "Bearded woman", unicode: "U+1F9D4" },
    { emoji: "👨‍🦰", description: "MAn with red hair", unicode: "U+1F468" },
    { emoji: "👨‍🦱", description: "Man with curly hair", unicode: "U+1F9B1" },
    { emoji: "👨‍🦳", description: "Man with white hair", unicode: "U+200D" },
    { emoji: "👨‍🦲", description: "Bald man", unicode: "U+1F468" },
    { emoji: "👩", description: "Woman", unicode: "U+1F469" },
    { emoji: "👩‍🦰", description: "Woman with red hair", unicode: "U+1F469" },
    { emoji: "👩‍🦱", description: "Woman with curly hair", unicode: "U+1F469" },
    { emoji: "👩‍🦳", description: "Woman with white hair", unicode: "U+1F469" },
    { emoji: "👩‍🦲", description: "Bald woman", unicode: "U+1F469" },
    { emoji: "👱‍♀‍", description: "Woman with blode hair", unicode: "U+1F471" },
    { emoji: "👱‍♂‍", description: "Man with blonde hair", unicode: "U+1F471" },
    { emoji: "🧓", description: "Old person", unicode: "U+1F9D3" },
    { emoji: "👴", description: "Old man", unicode: "U+1F474" },
    { emoji: "👵", description: "Old woman", unicode: "U+1F475" },
    { emoji: "🙍", description: "Person frowning", unicode: "U+1F64D" },
    { emoji: "🙍‍♂‍", description: "Man frowning", unicode: "U+1F64D" },
    { emoji: "🙍‍♀‍", description: "Woman frowning", unicode: "U+1F64D" },
    { emoji: "🙎", description: "Person pouting", unicode: "U+1F64E" },
    { emoji: "🙎‍♂‍", description: "Man pouting", unicode: "U+1F64E" },
    { emoji: "🙎‍♀‍", description: "Woman pouting", unicode: "U+1F64E" },
    { emoji: "🙅", description: "Person gesturing no", unicode: "U+1F645" },
    { emoji: "🙅‍♂‍", description: "Man gesturing no", unicode: "U+1F645" },
    { emoji: "🙅‍♀‍", description: "Woman gesturing no", unicode: "U+1F645" },
    { emoji: "🙆", description: "Person stretching", unicode: "U+1F646" },
    { emoji: "🙆‍♂‍", description: "Man stretching", unicode: "U+1F646" },
    { emoji: "🙆‍♀‍", description: "Woman stretching", unicode: "U+1F646" },
    { emoji: "💁", description: "Person tipping hand", unicode: "U+1F481" },
    { emoji: "💁‍♂‍", description: "Man tipping hand", unicode: "U+1F481" },
    { emoji: "💁‍♀‍", description: "Woman tipping hand", unicode: "U+1F481" },
    { emoji: "🙋", description: "Person rainsing hand", unicode: "U+1F64B" },
    { emoji: "🙋‍♂‍", description: "Man raising hand", unicode: "U+1F64B" },
    { emoji: "🙋‍♀‍", description: "Woman raisning hand", unicode: "U+1F64B" },
    { emoji: "🧏", description: "Deaf person", unicode: "U+1F64B" },
    { emoji: "🧏‍♂‍", description: "Deaf man", unicode: "U+1F9CF" },
    { emoji: "🧏‍♀‍", description: "Deaf woman", unicode: "U+2640" },
    { emoji: "🙇", description: "Person bowing", unicode: "U+1F647" },
    { emoji: "🙇‍♂‍", description: "Man bowing", unicode: "U+1F647" },
    { emoji: "🙇‍♀‍", description: "Woman bowing", unicode: "U+200D" },
    { emoji: "🤦", description: "Person facepalming", unicode: "U+1F926" },
    { emoji: "🤦‍♂‍", description: "Man facepalming", unicode: "U+1F926" },
    { emoji: "🤦‍♀‍", description: "Woman facepalming", unicode: "U+1F926" },
    { emoji: "🤷", description: "Person shrugging", unicode: "U+1F937" },
    { emoji: "🤷‍♂‍", description: "Man shrugging", unicode: "U+1F937" },
    { emoji: "🤷‍♀‍", description: "Woman shrugging", unicode: "U+FE0F" },
    { emoji: "💆", description: "Person getting massage", unicode: "U+1F486" },
    { emoji: "💆‍♂‍", description: "Man getting massage", unicode: "U+200D" },
    { emoji: "💆‍♀‍", description: "Woman getting massage", unicode: "U+2640" },
    { emoji: "💇", description: "Person getting haircut", unicode: "U+1F487" },
    { emoji: "💇‍♂‍", description: "Man getting haircut", unicode: "U+200D" },
    { emoji: "💇‍♀‍", description: "Woman getting haircut", unicode: "U+2640" },
    { emoji: "🚶", description: "Person walking", unicode: "U+1F6B6" },
    { emoji: "🚶‍♂‍", description: "Man walking", unicode: "U+200D" },
    { emoji: "🚶‍♀‍", description: "Woman walking", unicode: "U+FE0F" },
    { emoji: "🧍", description: "Person standing", unicode: "U+1F9CD" },
    { emoji: "🧍‍♂‍", description: "Man standing", unicode: "U+200D" },
    { emoji: "🧍‍♀‍", description: "Woman standing", unicode: "U+FE0F" },
    { emoji: "🧎", description: "Person kneeling", unicode: "U+1F9CE" },
    { emoji: "🧎‍♂‍", description: "Man kneeling", unicode: "U+200D" },
    { emoji: "🧎‍♀‍", description: "Woman kneeling", unicode: "U+FE0F" },
    { emoji: "🏃", description: "Person sprinting", unicode: "U+1F3C3" },
    { emoji: "🏃‍♂‍", description: "Man sprinting", unicode: "U+2642" },
    { emoji: "🏃‍♀‍", description: "Woman sprinting", unicode: "U+2640" },
    { emoji: "💃", description: "Woman dancing", unicode: "U+1F483" },
    { emoji: "🕺", description: "Man dancing", unicode: "U+1F57A" },
    { emoji: "🕴", description: "Person in suit levitating", unicode: "U+1F574" },
    { emoji: "👯", description: "People with bunny ears", unicode: "U+1F46F" },
    { emoji: "👯‍♂‍", description: "Men with bunny ears", unicode: "U+200D" },
    { emoji: "👯‍♀‍", description: "Women in bunny ears", unicode: "U+2640" },
    { emoji: "🧖", description: "Person in steaming room", unicode: "U+1F9D6" },
    { emoji: "🧖‍♂‍", description: "Man in steaming room", unicode: "U+200D" },
    { emoji: "🧖‍♀‍", description: "Woman in steaming room", unicode: "U+200D" },
    { emoji: "⛹", description: "Person bouncing ball", unicode: "U+26F9" },
    { emoji: "⛹️‍♂‍", description: "Man bouncing ball", unicode: "U+FE0F" },
    { emoji: "⛹️‍♀‍", description: "Woman bouncing ball", unicode: "U+2640" },
    { emoji: "🏋", description: "Person lifting weight", unicode: "U+1F3CB" },
    { emoji: "🏋️‍♂‍", description: "Man lifting weight", unicode: "U+FE0F" },
    { emoji: "🏋️‍♀‍", description: "Woman lifting weight", unicode: "U+2640" },
    { emoji: "🚴", description: "Person cycling", unicode: "U+1F6B4" },
    { emoji: "🚴‍♂‍", description: "Man cycling", unicode: "U+2642" },
    { emoji: "🚴‍♀‍", description: "Woman cycling", unicode: "U+FE0F" },
    { emoji: "🚵", description: "Person mountain biking", unicode: "U+1F6B5" },
    { emoji: "🚵‍♂‍", description: "Man mountain biking", unicode: "U+2642" },
    { emoji: "🚵‍♀‍", description: "Woman mountain biking", unicode: "U+2640" },
    { emoji: "🤸", description: "Person catwheeling", unicode: "U+1F938" },
    { emoji: "🤸‍♂‍", description: "Man catwheeling", unicode: "U+200D" },
    { emoji: "🤸‍♀‍", description: "Woman catwheeling", unicode: "U+FE0F" },
    { emoji: "🤼", description: "People wrestling", unicode: "U+1F93C" },
    { emoji: "🤼‍♂‍", description: "Men wrestling", unicode: "U+200D" },
    { emoji: "🤼‍♀‍", description: "Women wrestling", unicode: "U+2640" },
    { emoji: "🤽", description: "Person playing water polo", unicode: "U+1F93D" },
    { emoji: "🤽‍♂‍", description: "Man playing water polo", unicode: "U+FE0F" },
    { emoji: "🤽‍♀‍", description: "Woman playing water polo", unicode: "U+200D" },
    { emoji: "🤾", description: "Person playing handball", unicode: "U+1F93E" },
    { emoji: "🤾‍♂‍", description: "Man playing handball", unicode: "U+200D" },
    { emoji: "🤾‍♀‍", description: "Woman playing handball", unicode: "U+FE0F" },
    { emoji: "🤹", description: "Person juggling", unicode: "U+1F939" },
    { emoji: "🤹‍♂‍", description: "Man juggling", unicode: "U+200D" },
    { emoji: "🤹‍♀‍", description: "Woman juggling", unicode: "U+FE0F" },
    { emoji: "🧘", description: "Person lotus position", unicode: "U+1F9D8" },
    { emoji: "🧘‍♂‍", description: "Man in lotus position", unicode: "U+200D" },
    { emoji: "🧘‍♀‍", description: "Woman in lotus position", unicode: "U+2640" },
    { emoji: "🛀", description: "Person bathing", unicode: "U+1F6C0" },
    { emoji: "🛌", description: "Person in bed", unicode: "U+1F6CC" },
    { emoji: "👪", description: "Family", unicode: "U+1F46A" },
    { emoji: "👨‍👩‍👦", description: "Family: man, woman, and boy", unicode: "U+200D" },
    { emoji: "👨‍👩‍👧", description: "Family: man, woman, and girl", unicode: "U+1F469" },
    { emoji: "👨‍👩‍👧‍👦", description: "Family: man, woman, boy, and girl", unicode: "U+200D" },
    { emoji: "👨‍👩‍👦‍👦", description: "Family: man, woman, and two boys", unicode: "U+1F466" },
    { emoji: "👨‍👩‍👧‍👧", description: "Family: man, woman, and two girls", unicode: "U+200D" },
    { emoji: "👨‍👨‍👦", description: "Family: two men and boy", unicode: "U+1F466" },
    { emoji: "👨‍👨‍👧", description: "Family: two men and girl", unicode: "U+200D" },
    { emoji: "👨‍👨‍👧‍👦", description: "Family: two men, girl, and boy", unicode: "U+1F466" },
    { emoji: "👨‍👨‍👦‍👦", description: "Family: two men and two boys", unicode: "U+200D" },
    { emoji: "👨‍👨‍👧‍👧", description: "Family: two men and two girls", unicode: "U+1F467" },
    { emoji: "👩‍👩‍👦", description: "Family: two women and boy", unicode: "U+1F466" },
    { emoji: "👩‍👩‍👧", description: "Family: two women and girl", unicode: "U+1F467" },
    { emoji: "👩‍👩‍👧‍👦", description: "Family: two women, girl, and boy", unicode: "U+1F466" },
    { emoji: "👩‍👩‍👦‍👦", description: "Family: two women and two boys", unicode: "U+1F466" },
    { emoji: "👩‍👩‍👧‍👧", description: "Family: two women and two girls", unicode: "U+1F467" },
    { emoji: "👨‍👦", description: "Family: man and boy", unicode: "U+1F466" },
    { emoji: "👨‍👦‍👦", description: "Family: man and two boys", unicode: "U+1F466" },
    { emoji: "👨‍👧", description: "Family: man and girl", unicode: "U+1F467" },
    { emoji: "👨‍👧‍👦", description: "Family: man, girl and boy", unicode: "U+1F466" },
    { emoji: "👨‍👧‍👧", description: "Family: man and two girls", unicode: "U+1F467" },
    { emoji: "👩‍👦", description: "Family: woman and boy", unicode: "U+1F466" },
    { emoji: "👩‍👦‍👦", description: "Family: woman and two boys", unicode: "U+1F466" },
    { emoji: "👩‍👧", description: "Family: woman and girl", unicode: "U+1F467" },
    { emoji: "👩‍👧‍👦", description: "Family: woman, girl, and boy", unicode: "U+1F466" },
    { emoji: "👩‍👧‍👧", description: "Family: woman and two girls", unicode: "U+1F467" },
    { emoji: "🧑‍🤝‍🧑", description: "People holding hands", unicode: "U+1F9D1" },
    { emoji: "👭", description: "Women holding hands", unicode: "U+1F46D" },
    { emoji: "👫", description: "Woman and man holding hands", unicode: "U+1F46B" },
    { emoji: "👬", description: "Men holding hands", unicode: "U+1F46C" },
    { emoji: "💏", description: "Kiss", unicode: "U+1F48F" },
    { emoji: "👩‍❤‍💋‍👨", description: "Woman and man kissing", unicode: "U+200D" },
    { emoji: "👨‍❤‍💋‍👨", description: "Man and man kissing", unicode: "U+200D" },
    { emoji: "👩‍❤‍💋‍👩", description: "Womand and woman kissing", unicode: "U+1F48B" },
    { emoji: "💑", description: "Couple with heart", unicode: "U+1F491" },
    { emoji: "🗣", description: "Person speaking", unicode: "U+1F5E3" },
    { emoji: "👤", description: "Bust in silhouhette", unicode: "U+1F464" },
    { emoji: "👥", description: "Busts in silhouette", unicode: "U+1F465" },
    { emoji: "👋", description: "Waving hand", unicode: "U+1F44B" },
    { emoji: "🤚", description: "Raised back of hand", unicode: "U+1F91A" },
    { emoji: "🖐", description: "Hands with splayed finger", unicode: "U+1F590" },
    { emoji: "✋", description: "Raised hand", unicode: "U+270B" },
    { emoji: "🖖", description: "Vulcan salute", unicode: "U+1F596" },
    { emoji: "👌", description: "Ok", unicode: "U+1F44C" },
    { emoji: "🤏", description: "Pinched hand", unicode: "U+1F90F" },
    { emoji: "✌", description: "Victory hand", unicode: "U+270C" },
    { emoji: "🤞", description: "Crossed fingers", unicode: "U+1F91E" },
    { emoji: "🤟", description: "Love you", unicode: "U+1F91F" },
    { emoji: "🤘", description: "Horn sign", unicode: "U+1F918" },
    { emoji: "🤙", description: "Call me hand", unicode: "U+1F919" },
    { emoji: "👈", description: "Index finger pointing left", unicode: "U+1F448" },
    { emoji: "👉", description: "Index finger pointing right", unicode: "U+1F449" },
    { emoji: "👆", description: "Index finger pointing up", unicode: "U+1F446" },
    { emoji: "👇", description: "Index finger pointing down", unicode: "U+1F447" },
    { emoji: "🖕", description: "Middle finger", unicode: "U+1F595" },
    { emoji: "☝", description: "Forehand Index finger pointing up", unicode: "U+261D" },
    { emoji: "👍", description: "Thumbs up", unicode: "U+1F44D" },
    { emoji: "👎", description: "Thumbs down", unicode: "U+1F44E" },
    { emoji: "✊", description: "Raised fist", unicode: "U+270A" },
    { emoji: "👊", description: "Fist", unicode: "U+1F44A" },
    { emoji: "🤛", description: "Left facing fist", unicode: "U+1F91B" },
    { emoji: "🤜", description: "Right facing fist", unicode: "U+1F91C" },
    { emoji: "👏", description: "Clapping hands", unicode: "U+1F44F" },
    { emoji: "🙌", description: "Raised hands", unicode: "U+1F64C" },
    { emoji: "👐", description: "OPen hands", unicode: "U+1F450" },
    { emoji: "🤲", description: "Palms together hands", unicode: "U+1F932" },
    { emoji: "🤝", description: "Handshake", unicode: "U+1F91D" },
    { emoji: "🙏", description: "Praying hands", unicode: "U+1F64F" },
    { emoji: "✍", description: "Writing hands", unicode: "U+270D" },
    { emoji: "💪", description: "Flexed biceps", unicode: "U+1F4AA" },
    { emoji: "👀", description: "Eyes", unicode: "U+1F440" },
    { emoji: "💋", description: "Kiss", unicode: "U+1F48B" },
    { emoji: "💌", description: "Love letter", unicode: "U+1F48C" },
    { emoji: "💘", description: "Heart with arrow", unicode: "U+1F498" },
    { emoji: "💝", description: "HEart with ribbon", unicode: "U+1F49D" },
    { emoji: "💖", description: "Sparking heart", unicode: "U+1F496" },
    { emoji: "💗", description: "Growing heart", unicode: "U+1F497" },
    { emoji: "💓", description: "Beating heart", unicode: "U+1F493" },
    { emoji: "💞", description: "Revolving heart", unicode: "U+1F49E" },
    { emoji: "💕", description: "Two hearts", unicode: "U+1F495" },
    { emoji: "💟", description: "Heart decoration", unicode: "U+1F49F" },
    { emoji: "❣", description: "Heart exclamation", unicode: "U+2763" },
    { emoji: "💔", description: "Broken heart", unicode: "U+1F494" },
    { emoji: "❤️‍🔥", description: "Heart on fire", unicode: "U+2764" },
    { emoji: "❤️‍🩹", description: "Mending heart", unicode: "U+2764" },
    { emoji: "❤", description: "Red heart", unicode: "U+2764" },
    { emoji: "🧡", description: "Orange heart", unicode: "U+1F9E1" },
    { emoji: "💛", description: "Yellow heart", unicode: "U+1F49B" },
    { emoji: "💚", description: "Green heart", unicode: "U+1F49A" },
    { emoji: "💙", description: "Blue heart", unicode: "U+1F499" },
    { emoji: "💜", description: "Purple heart", unicode: "U+1F49C" },
    { emoji: "🤎", description: "Brown heart", unicode: "U+1F90E" },
    { emoji: "🖤", description: "Black heart", unicode: "U+1F5A4" },
    { emoji: "🤍", description: "White heart", unicode: "U+1F90D" },
    { emoji: "💯", description: "Hundred(correct)", unicode: "U+1F4AF" },
    { emoji: "💢", description: "Anger", unicode: "U+1F4A2" },
    { emoji: "💥", description: "collision", unicode: "U+1F4A5" },
    { emoji: "💦", description: "Sweat droplets", unicode: "U+1F4A6" },
    { emoji: "🌍", description: "Globe showing Africa and Europe", unicode: "U+1F30D" },
    { emoji: "🌎", description: "Globe showing Americas", unicode: "U+1F30E" },
    { emoji: "🌏", description: "Globe showing Asia and Australia", unicode: "U+1F30F" },
    { emoji: "🌒", description: "Waxing crescent moon", unicode: "U+1F312" },
    { emoji: "🌓", description: "First quarter moon", unicode: "U+1F313" },
    { emoji: "🌔", description: "Waxing gibbous moon", unicode: "U+1F314" },
    { emoji: "🌕", description: "Full moon", unicode: "U+1F315" },
    { emoji: "🌖", description: "Waning gibbous moon", unicode: "U+1F316" },
    { emoji: "🌗", description: "Last quarter moon", unicode: "U+1F317" },
    { emoji: "🌘", description: "Waning crescent moon", unicode: "U+1F318" },
    { emoji: "🌙", description: "Crescent moon", unicode: "U+1F319" },
    { emoji: "🌚", description: "New moon face", unicode: "U+1F31A" },
    { emoji: "🌛", description: "First quarter moon face", unicode: "U+1F31B" },
    { emoji: "🌜", description: "Last quartermoon face", unicode: "U+1F31C" },
    { emoji: "🌝", description: "Full moon face", unicode: "U+1F31D" },
    { emoji: "🌞", description: "Sun with face", unicode: "U+1F31E" },
    { emoji: "⭐", description: "Star", unicode: "U+2B50" },
    { emoji: "☁", description: "Cloud", unicode: "U+2601" },
    { emoji: "⚡", description: "High voltage", unicode: "U+26A1" },
    { emoji: "❄", description: "Snowflake", unicode: "U+2744" },
    { emoji: "🔥", description: "Fire", unicode: "U+1F525" },
    { emoji: "🎃", description: "Jack-o-lantern", unicode: "U+1F383" },
    { emoji: "🎄", description: "Christmas tree", unicode: "U+1F384" },
    { emoji: "🎆", description: "Fireworks", unicode: "U+1F386" },
    { emoji: "🎇", description: "Sparkler", unicode: "U+1F387" },
    { emoji: "🧨", description: "Firecracker", unicode: "U+1F9E8" },
    { emoji: "✨", description: "Sparkles", unicode: "U+2728" },
    { emoji: "🎈", description: "Baloon", unicode: "U+1F388" },
    { emoji: "🎉", description: "Party popper", unicode: "U+1F389" },
    { emoji: "🎊", description: "Confetti ball", unicode: "U+1F38A" },
    { emoji: "⚽", description: "Soccer ball", unicode: "U+26BD" },
    { emoji: "⚾", description: "Baseball", unicode: "U+26BE" },
    { emoji: "🥎", description: "Softball", unicode: "U+1F94E" },
    { emoji: "🏀", description: "BAsketball", unicode: "U+1F3C0" },
    { emoji: "🏐", description: "Volleyball", unicode: "U+1F3D0" },
    { emoji: "🏈", description: "American football", unicode: "U+1F3C8" },
    { emoji: "🏉", description: "Rugby", unicode: "U+1F3C9" },
    { emoji: "🎾", description: "Tennis", unicode: "U+1F3BE" },
    { emoji: "🥏", description: "Flying disk", unicode: "U+1F94F" },
    { emoji: "🎳", description: "Bowling", unicode: "U+1F3B3" },
]
